# Generated by Django 5.1 on 2024-09-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_category_alter_todo_created_at_todo_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название задания'),
        ),
    ]
