# Generated by Django 5.1 on 2024-09-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('L', 'Низкий'), ('M', 'Средний'), ('H', 'Высокий')], default='L', max_length=1, verbose_name='Приоритет'),
        ),
    ]
